# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: 首页
  url: /
  icon:
- page: 前端
  url: /
  icon:
- page: 后端
  url: /java
  icon:
- page: 工具
  url: /
  icon: 
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /img/favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: './img/head-img.jpg'
  url: 'javascript:'

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>
                <strong>You got a dream, you got to protect it.
                People can't do something by themselves,they wanna tell you you can not do it.
                You want something. Go get it！</strong><br/>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/aiceflower
 - name: 邮箱
   icon: envelope-o
   href: /
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微信
   icon: weixin
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: true

## 友链设置
links:
    - Java指导[Java学习+面试指南]: https://github.com/Snailclimb/JavaGuide
    - Java工程师进阶扫盲: https://github.com/doocs/advanced-java


# 主题自定义个性化配置

## 网站宣传语
branding:
    一双手 + 一棵豆子 = 改变世界

## 设置banner背景图片
banner:
   img: /img/top_one.png

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  - /img/top_one.png
  - /img/top_two.jpg

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: false

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://aiceflower.github.io" target="_blank">Aiceflower</a>

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 请我吃个棒棒糖吧!

## 主题评论

## Valine评论
valine:
   enable: true
   appId: "g1eM9mmyQl9uzKaeWIfVcsss-gzGzoHsz"
   appKey: "ye7F7MwDY0J48QeJCppYu7Xd"
   placeholder: 欢迎来撩... 
   notify: false
   verify: false
   avatar: mm
   meta: aiceflower,aiceflower@sina.com
   pageSize: 10
  
### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
   enable: false
   clientID: fcdb03dfcad397761a4d
   clientSecret: 5a2eff53c51838a269667eb7237562cbdafa3395
   repo: hexo-comment
   owner: aiceflower
   admin: aiceflower
   perPage: 10
   id:

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计
visit_counter:
   site: false
   page: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
